CREATE TABLE person (
	id BIGINT(20) NOT NULL AUTO_INCREMENT,
    code VARCHAR(36) NOT NULL,
    name VARCHAR(50) NOT NULL,
    active BOOLEAN NOT NULL,
    PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8