ALTER TABLE person ADD street VARCHAR(100) NULL;
ALTER TABLE person ADD num VARCHAR(15) NULL;
ALTER TABLE person ADD complement VARCHAR(50) NULL;
ALTER TABLE person ADD district VARCHAR(50) NULL;
ALTER TABLE person ADD postalCode VARCHAR(8) NULL;
ALTER TABLE person ADD city VARCHAR(50) NULL;
ALTER TABLE person ADD state VARCHAR(50) NULL;